### ISSUE TITLE
Computed tag based on old tag

### ISSUE THREAD

**Issue by Gethe** [craig-day/compute-tag#8]
[This is the run](https://github.com/RealUI/RealUI/actions/runs/447914681)

The log portion for this action:
```
Run craig-day/compute-tag@v10
  with:
    github_token: ***
    version_scheme: semantic
    version_type: prerelease
    prerelease_suffix: beta
Computing the next tag based on: 8.1_r20
Computed the next tag as: 8.1.1-beta.0
```

That tag is over three years, and many tags old

**Comment by craig-day** [comment]
@Gethe sorry I missed this issue. Is that tag newer than your current tagging scheme? This happens because of the way GitHub's API returns tags in lexicographic order, not order by creation date or order on the tree. I'm actually actively working on a feature for you to specify the branch to use when computing tags so it will iterate the commits on a branch starting with HEAD and work back in time until it finds a commit with a tag.

**Comment by Gethe** [comment]
No, that was an old tag from before I switched to semver early last year.

**Comment by craig-day** [comment]
I believe this is solved given the changes to how tags and releases are pulled. I'm going to close it for now, please re-open if the issue persists.
